### ISSUE TITLE
Drop or patch dependency import-fresh

### ISSUE THREAD

**Issue by legobeat** [eslint/eslintrc#110]
The dependency `import-fresh` seems unmaintained (last commit and release in 2020) and is starting to show its age, with opened issues going unattended.

https://github.com/sindresorhus/import-fresh/issues

Consider either addressing the issue in the dependency (ideally upstreamed, or replace it with an alternative.

**Comment by nzakas** [comment]
Unless there's a problem with a given dependency, we don't replace it.
