### ISSUE TITLE
Missing parameter 'recommendedConfig' in FlatCompat constructor

### ISSUE THREAD

**Issue by meeroslav** [eslint/eslintrc#127]
## Environment:
- eslint: `8.46.0`
- @eslint/eslintrc: `2.1.1`
- OS: macOS

## Steps to reproduce:
- `packages/mylib/eslint.config.js`
```js
const baseConfig = require('../../eslint.config.js');
const jsoncEslintParser = require('jsonc-eslint-parser');

module.exports = [
  baseConfig,
  {
    files: ['packages/mylib/**/*.json'],
    languageOptions: {
      parser: jsoncEslintParser,
    },
    rules: { '@nx/dependency-checks': 'error' },
  },
];
```

- `eslint.config.js`:
```js
const nxEslintPlugin = require('@nx/eslint-plugin');
const { FlatCompat } = require('@eslint/eslintrc');
const globals = require('globals');

const compat = new FlatCompat({
  baseDirectory: __dirname
});

module.exports = [
  { plugins: { '@nx': nxEslintPlugin } },
  {
    files: ['**/*.ts', '**/*.tsx'],
    ...compat.extends('plugin:@nx/typescript'),
    rules: {},
  },
  {
    files: ['**/*.js', '**/*.jsx'],
    ...compat.extends('plugin:@nx/javascript'),
    rules: {},
  },
  { ignores: ['node_modules'] },
];
```

## Current
Reports TypeError: Missing parameter 'recommendedConfig' in FlatCompat constructor.

## Expected
The 'recommendedConfig' is not needed since docs mark it as optional

**Comment by aladdin-add** [comment]
is it reported by typescript?  

I think you will have to file it in DT - the typings are not maintained by the eslint team. :)

**Comment by meeroslav** [comment]
@aladdin-add the error comes from this line so it's not coming from DT:
https://github.com/eslint/eslintrc/blob/main/lib/flat-compat.js#L233

**Comment by aladdin-add** [comment]
well I see, definitely a bug, thanks!

**Comment by mdjermanovic** [comment]
> Reports TypeError: Missing parameter 'recommendedConfig' in FlatCompat constructor.

This works as expected because the eslintrc configurations you're translating extend `'eslint:recommended'`:

https://github.com/nrwl/nx/blob/bb76d01942fbf33468b19b7be3262dd8523e6390/packages/eslint-plugin/src/configs/typescript.ts#L23

https://github.com/nrwl/nx/blob/bb76d01942fbf33468b19b7be3262dd8523e6390/packages/eslint-plugin/src/configs/javascript.ts#L34

In this case, passing in `recommendedConfig` is mandatory. Perhaps we should clarify that in the docs.
