### ISSUE TITLE
Recommendations Needed for Using FlatCompat in CommonJS eslint Configs

### ISSUE THREAD

**Issue by rostislav-simonik** [eslint/eslintrc#133]
We are currently working on migrating our eslint configs to flat configs, but are facing a high level of complexity in the process. I'm seeking recommendations or best practices on how to effectively use FlatCompat in CommonJS eslint configs.

Utilization of FlatCompat in CommonJS:

* How can FlatCompat be effectively used within CommonJS eslint configs? 
* Are there any best practices or recommended approaches to facilitate this integration?

Support for CommonJS Projects:

* Has consideration been given to publishing the FlatCompat utility with support specifically for CommonJS projects?

Your insights and advice regarding these queries will be greatly valuable and appreciated.

**Comment by nzakas** [comment]
In CommonJS, you can just use `require()`:

```js
const { FlatCompat } = require("@eslint/eslintrc");
```

Otherwise, you can use the example in the README mostly as-is. We can probably update that with a CommonJS example to avoid confusion.

**Comment by rostislav-simonik** [comment]
Thanks, yes, that was one of the things that was crucial to proceed further. Now, we are battling how to integrate `eslint-config-standard-with-typescript` and other configs using FlatCompat. There are a few concerns about that here https://github.com/typescript-eslint/typescript-eslint/issues/7694, but it looks promising on our side so far.
