### ISSUE TITLE
`FlatCompat#env({es2024: true})` missing builtin globals

### ISSUE THREAD

**Issue by fisker** [eslint/eslintrc#146]
```js
new (require('@eslint/eslintrc').FlatCompat)().env({es2024: true})[0]
{
  languageOptions: {
    globals: {
      ArrayBuffer: false,
      DataView: false,
      Float32Array: false,
      Float64Array: false,
      Int16Array: false,
      Int32Array: false,
      Int8Array: false,
      Map: false,
      Promise: false,
      Proxy: false,
      Reflect: false,
      Set: false,
      Symbol: false,
      Uint16Array: false,
      Uint32Array: false,
      Uint8Array: false,
      Uint8ClampedArray: false,
      WeakMap: false,
      WeakSet: false,
      Atomics: false,
      SharedArrayBuffer: false,
      BigInt: false,
      BigInt64Array: false,
      BigUint64Array: false,
      globalThis: false,
      AggregateError: false,
      FinalizationRegistry: false,
      WeakRef: false
    },
    ecmaVersion: 15
  }
}
```

Shouldn't objects like `Array` includes?

**Comment by ljharb** [comment]
Is there any version of JS that eslint supports that wouldn't have `Array` as a global by default?

**Comment by mdjermanovic** [comment]
In eslintrc, these environments contained only globals added after es5, and es5 globals were always automatically enabled.

In flat config mode, `ecmaVersion: 15` alone automatically  enables all [es2024 globals](https://github.com/eslint/eslint/blob/bde51055530d4a71bd9f48c90ed7de9c0b767d86/conf/globals.js#L131-L133) (including `Array`)  .

Even if another config object overrides `ecmaVersion` to a lower version, at least [es3 globals](https://github.com/eslint/eslint/blob/bde51055530d4a71bd9f48c90ed7de9c0b767d86/conf/globals.js#L19) (including `Array`) will always be automatically enabled.

Is there something in particular that doesn't work for you when you use `FlatCompat` with a configuration that has `es2024: true`?

**Comment by fisker** [comment]
> es5 globals were always automatically enabled.

Good to know.
