### ISSUE TITLE
[Bug] Cannot redefine plugin "vue" error

### ISSUE THREAD

**Issue by matthew-dean** [eslint/eslintrc#149]
I'm getting this issue:
```
TypeError: Cannot redefine plugin "vue".
    at ObjectSchema.merge
```

I thought it might be because I have this in my root:
```
    files: ['*.ts', '*.tsx', '*.vue'],
    languageOptions: {
      parser: VueEsLintParser,
      parserOptions: {
        parser: TSParser,
        project: './tsconfig.json',
        extraFileExtensions: ['.vue']
      }
    },
```
... and then I have this in a sub-project (in my monorepo)

```
files: ['*.js', '*.ts', '*.tsx', '*.vue'],
    languageOptions: {
      parser: VueEsLintParser,
      parserOptions: {
        parser: TSParser,
        project: './tsconfig.json',
        extraFileExtensions: ['.vue']
      },
```
However, note that this should override the previous definition, and these are all local imports. This worked with the old file format, and I feel like it's perfectly valid for monorepos, especially as you might have different versions of Vue (and thus Vue parsers) in different projects.

Also note: I removed the base config definition, yet I'm still having this issue.

**Comment by aladdin-add** [comment]
can you provide a repro, thanks! 🙏

**Comment by nzakas** [comment]
No repro, so closing.
