### ISSUE TITLE
Test built-in rule schema validation

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslintrc#15]
refs https://github.com/eslint/eslintrc/pull/14

ESLint should validate configuration for built-in rules, and throw if the configuration is invalid.

We had a regression described in https://github.com/eslint/eslint/issues/13793, due to the lack of tests for this scenario.

An integration test has been added in the eslint/eslint repo (eslint/eslint#13794), but we should add some unit tests to this repository, too.

**Comment by nzakas** [comment]
@mdjermanovic do you have a plan for what to do here?

**Comment by mdjermanovic** [comment]
I'm working on this.
