### ISSUE TITLE
Fix: Validate options after applying defaults, not before

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [eslint/eslintrc#165]
Coming over from https://github.com/eslint/eslint/pull/17656#issuecomment-2027532264: right now, eslintrc validates options and _then_ validates defaults. Copying the example from @mdjermanovic's comment, if this is a rule:

```js
{
    meta: {
        defaultOptions: [{
            foo: 42
        }],
        schema: [{
            type: "object",
            maxProperties: 2 // allows one or two in addition to "foo"?
        }]
    },
    create() {
        return {};
    }
}
```

...then the configuration `["error", { bar: 6, baz: 7 }]` is still considered valid.

This is different from the new ESLint flat config format.

Technically this proposed stricter behavior could be considered a breaking change and out of scope given this package's feature freeze. However, I'd propose we consider it a bugfix, as IMO the invalid options should not have been allowed to begin with.

Filing a tracking issue for my reference. I plan on sending a PR for this soon, unless directed otherwise.

**Comment by mdjermanovic** [comment]
> Technically this proposed stricter behavior could be considered a breaking change

Can you clarify this? `meta.defaultOptions` is a new feature, so I believe there is no previous behavior compared to which this would be a breaking change.

**Comment by JoshuaKGoldberg** [comment]
> Can you clarify this? `meta.defaultOptions` is a new feature, so I believe there is no previous behavior compared to which this would be a breaking change.

Oh, I was thinking if a rule happened to already have `meta.defaultOptions` defined by coincidence. But you're right that this shouldn't affect any properly written existing rules.
