### ISSUE TITLE
Package deleted from npm?

### ISSUE THREAD

**Issue by tomups** [eslint/eslintrc#175]
Getting 404 on https://www.npmjs.com/package/@eslint/eslintrc and can't install as dependency

**Comment by tomups** [comment]
Seems it's back now :)

**Comment by nzakas** [comment]
It looks like there was some kind of issue with npm about 20 hours ago.

FWIW, npm doesn't allow deletion of packages.

**Comment by tomups** [comment]
Indeed, seems there was a scheduled infra update https://status.npmjs.org/incidents/px35z3dmcjgm
