### ISSUE TITLE
TypeError: Ajv is not a constructor

### ISSUE THREAD

**Issue by benmonro** [eslint/eslintrc#21]
not sure where this error is exactly coming from but my open source project (eslint-plugin-jest-dom) uses kcd-scripts which in turn executes eslint.  when we run lint in that way we see the following error: 

```
FAIL src/__tests__/lib/rules/prefer-in-document.js
[test]   ● Test suite failed to run
[test] 
[test]     TypeError: Ajv is not a constructor
[test] 
[test]       at Object.<anonymous>.module.exports (node_modules/@eslint/eslintrc/lib/shared/ajv.js:19:17)
```

you can see the issue here:
https://github.com/testing-library/eslint-plugin-jest-dom/runs/1476579289?check_suite_focus=true

**Comment by nzakas** [comment]
Sorry we missed this. I believe this issue has been resolved.

**Comment by GiancarlosIO** [comment]
I'm having the same error 🤔 . I'm using eslint 7.19.0

**Comment by nzakas** [comment]
@GiancarlosIO please open an issue in the main ESLint repo

**Comment by nickmccurdy** [comment]
If anyone is still having this issue, it's probably caused by `'shared'` in `moduleDirectories` within your Jest config.
