### ISSUE TITLE
Why is this a legacy package?

### ISSUE THREAD

**Issue by DanielSWolf** [eslint/eslintrc#22]
I'm trying to understand the inner workings of ESLint, particularly the way the `extends` mechanism is implemented. It is my understanding that this package implements all parsing of configuration files. However, the README states (emphasis mine):

> This repository contains the **legacy** ESLintRC configuration file format for ESLint.

What exactly does "legacy" mean in this context?

* Is there another package for parsing *.eslintrc.** files somewhere else that I missed, so that this package is considered deprecated?
* Are the *.eslintrc.** file formats themselves considered deprecated and there is a new, better configuration format?

**Comment by nzakas** [comment]
ESLintRC is the current config file format and is being replaced. The first step was to extract it into its own package. See the [RFC](https://github.com/eslint/rfcs/tree/master/designs/2019-config-simplification) for more details.
