### ISSUE TITLE
The `files` setting with base configs

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslintrc#27]
From https://github.com/eslint/eslint/issues/8813

The `extends` setting in the `overrides` section was a long-standing issue and it's a popular feature now.

Currently, the flat config doesn't provide an easy way for that.
I think a solution is the following one:

```js
import baseConfig from "my-eslint-config"
import mocha from "eslint-plugin-mocha"
export default [
  baseConfig.base,
  {
    "files": ["/scripts/**", "/server/**"],
    "configs": [baseConfig.node], // may have different settings for CJS and ESM. Also, it mey be a function to check `${cwd}/package.json`'s module type.
  },
  {
    "files": ["/client/**/*"],
    "configs": [baseConfig.browser],
  },
  {
    "files": ["/test/**/*.js"],
    "configs": [baseConfig.node, mocha.configs.recommended],
  },
]
```

It just merges the `files` properties in the flattening phase by [AND patterns](https://github.com/eslint/rfcs/tree/master/designs/2019-config-simplification#using-and-patterns-for-files).

**Comment by chalkygames123** [comment]
@nzakas Sorry for pinging you, but is there any tracker for this in the main repository?

**Comment by nzakas** [comment]
Yes thanks, this is the issue:
https://github.com/eslint/eslint/issues/16537

There is already an open pull request for it.
