### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by mohitkumat-mu** [eslint/eslintrc#4]
https://github.com/eslint/eslintrc/blob/10965bc84e352eb114e966763bd8747e5120204a/conf/environments.js#L26

Trying to migrate from eslint 3.19.0 to 7.8.0, the above line throws error for value of `current` (globals.es2015) object:

`TypeError: Cannot convert undefined or null to object`

**Comment by nzakas** [comment]
Fixed by #5
