### ISSUE TITLE
Upgrade Espree

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslintrc#41]
eslintrc has espree as a dependency, so when we start with v8.0.0 prereleases we should update [`package.json`](https://github.com/eslint/eslintrc/blob/af96cc5494962c9d3961c0da0f97bfb3e8b81c59/package.json#L52) here.

Unless in the meantime we figure out how to remove the dependency on espree, if possible.

**Comment by nzakas** [comment]
Unless I'm missing something, it appears Espree isn't actually used anywhere in the repo. Probably safe to just remove it.

**Comment by mdjermanovic** [comment]
It's used [here](https://github.com/eslint/eslintrc/blob/7c43d7784e39cf0b7b102af64f703cade11252bb/lib/config-array-factory.js#L946).

The logic is - when user sets `parser: "espree"` in their config, first try to resolve it the same way as third-party parsers are resolved. If that fails for whatever reason, load ESLint's version.

This was originally added in https://github.com/eslint/eslint/commit/25cc63d47e6c0aea8b88589a088c1f0de5f6f1cc (a commit within the pull request: https://github.com/eslint/eslint/pull/11388/commits/901d60fe8c27ed8bc1a7bf5a10a1099ea350e913).

https://github.com/eslint/rfcs/tree/main/designs/2018-simplified-package-loading

> There is one exception: If a config specifies the string "espree" as a parser, but the espree package cannot be loaded from the config, then ESLint's espree dependency will be used as a fallback instead of throwing a fatal error. This exception exists to provide compatibility for shareable configs that explicitly specify parser: "espree" with the intention of using the package bundled with ESLint.

**Comment by nzakas** [comment]
Ah gotcha

**Comment by nzakas** [comment]
Working on this.
