### ISSUE TITLE
ESLint Browser Test fails

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslintrc#50]
The current `main` branch of `@eslint/eslintrc` breaks Browser Test in `eslint/eslint`. Consequently, the ESLint demo won't work.

https://github.com/eslint/eslint/pull/14865#issuecomment-893561539

How to reproduce locally:

1. Check out the branch from https://github.com/eslint/eslint/pull/14865
2. Run `node Makefile.js karma`

The fix might include some updates in `eslint/eslintrc` repo and/or updates in `webpack.config.js` in `eslint/eslint` repo. I tried several approaches and nothing worked (fixing some errors always produces new errors).

I'd suggest reverting https://github.com/eslint/eslintrc/pull/39.

**Comment by nzakas** [comment]
Running `node Makefile.js webpack` is a faster option.

**Comment by nzakas** [comment]
This is happening because `./lib/linter.js` in ESLint is including all of `@eslint/eslintrc`, including the Node.js-specific functionality. We can work around this by creating a separate entrypoint in `@eslint/eslintrc` that just exposes what we need in linter for browser-specific functionality.
