### ISSUE TITLE
`eslintrc` brings in a different version of `js-yaml` than `eslint`

### ISSUE THREAD

**Issue by lopopolo** [eslint/eslintrc#59]
`@eslint/eslintrc` depends on `js-yaml@^3.13.1`.

https://github.com/eslint/eslintrc/blob/b657ceafd64f2d5842b5c2d3d660cfd57660cd06/package.json#L74

`eslint` depends on `js-yaml@^4.1.0`.

https://github.com/eslint/eslint/blob/796587ad950f6804d60473c2b5998ed3ec71c59e/package.json#L74

This means that `eslint` brings in two semver incompatible versions of `js-yaml` into the lockfile.

Proposed fix: update the `js-yaml` dependency in this package to have the same version constraint as that in `eslint`.

**Comment by lopopolo** [comment]
this dependency mismatch also results in two semver incompatible versions of `argparse` appearing in the lockfile.

**Comment by nzakas** [comment]
Sounds good to me. Can you send a pull request?

**Comment by lopopolo** [comment]
> Can you send a pull request?

I tried, but I'd like to decline this ask to avoid signing a contract for the CLA.
