### ISSUE TITLE
call createRequire lazily 

### ISSUE THREAD

**Issue by jimmywarting** [eslint/eslintrc#63]
I have some success to load eslint using `import('https://jspm.dev/eslint@7')` and running it too without any eslint config file in the browser. (I'm using `useEslintrc: false`)

version 8 don't work as grate, think it boils down to this:
https://github.com/eslint/eslintrc/blob/731fa4993e3b37d703cf2ba4f03429f89ae6e0a2/lib/config-array-factory.js#L57

...and also the fact that jspm don't support dynamic `require()` very well...

the best thing would be to not use `createRequire` at all and... they should be loaded async with `import()` instead... but lets not be hanged up on this too much... cuz it require to much refactoring and breakage.

I think the quickest and easiest solution would be to do: 

```js
require = (...args) => createRequire(import.meta.url)(...args)
```
is this 👆 something you could quickly impl?

---

currently `import('https://jspm.dev/eslint@7')` dose not call any `require()`.
i still have yet to figure out how to manually add some eslint plugin without using the rules config that are limited to plain objects.

**Comment by nzakas** [comment]
I'm sorry, I can't tell from your description what it is you're trying to do and how such a change would help. Can you explain in more detail?

**Comment by jimmywarting** [comment]
Trying to do this:
![image](https://user-images.githubusercontent.com/1148376/143280035-133e9d70-93a7-4ce7-ab96-32aa2b79442b.png)

I guess the problem could be solved if you just don't call the  `module.createRequire(...)` at all
importing `createRequire` from module and not doing anything with it would be fine.

That is why i'm suggesting a simple wrapper function that calls `createRequire` lazily (when needed)

**Comment by jimmywarting** [comment]
think this code works fine:

```js
// create require lazily to fix jspm
// eslint-disable-next-line func-style
let require = pkg => {
    require = createRequire(import.meta.url);
    return require(pkg);
};
```

**Comment by nzakas** [comment]
I’m still having trouble understanding why you’d want to do such a thing. What’s the use case?

It also seems like this is a bug in JSPM?

**Comment by jimmywarting** [comment]
yea, it's a bug with jspm...

my simple usecase is that i would like to import eslint in the browser using a cdn+import, this is the only bit that prevents me from being able to load eslint@8 from jspm

eslint@7 did not have any createRequire stuff

**Comment by ljharb** [comment]
Is there an open issue on jspm about supporting createRequire?

**Comment by jimmywarting** [comment]
created one 2 days ago: https://github.com/jspm/babel-plugin-transform-cjs-dew/issues/15

**Comment by nzakas** [comment]
We don’t intend to support loading the eslint package directly in the browser like this. Your best bet is to get jspm to fix the bug.
