### ISSUE TITLE
copyight holder seems not a legal entity

### ISSUE THREAD

**Issue by jonassmedegaard** [eslint/eslintrc#67]
The file LICENSE states the following:
> Copyright (c) 2020 ESLint

I am not a lawyer, but can only understand that sentence as "ESLint claims to hold legal copyright over substantial inventive work done in 2020".

Is "ESLint" even a legal entity that can claim copyright?

The Project ESLint says that another legal entity - "JS Foundation" - holds copyright for that.

It is worth noting that [since 1989](https://en.wikipedia.org/wiki/Copyright#Copyright_notice)  the very act of writing such copyright notice is no longer a legal requirement - copyright is implicit nowadays - and the main reason to do it anyway is as a courtesy for users to let them know who they *likely* will need to contact if they want to negotiate an unusual deal (i.e. relicensing).

I guess that the a more accurate copyright notice would be same as for ESLint, since this project seems to be a fork of a subset of that other project.

**Comment by nzakas** [comment]
Yeah, this should be the same copyright as the main ESLint repo. I’m not sure how it got messed up in the migration.
