### ISSUE TITLE
config-array "mergeWithoutOverwrite" make linting fail by transforming Regex into empty object

### ISSUE THREAD

**Issue by dmnsgn** [eslint/eslintrc#75]
**Issue**

When using eslint programmatically, we're allowed to pass parserOptions as an object. If this object contains a regex, it will be transformed to an empty object (following eslint calling extractConfig in linter `verify -> _verifyWithConfigArray` [here](https://github.com/eslint/eslint/blob/76a235a31718312c2ed202fdde030d329ca62486/lib/linter/linter.js#L1710-L1714)) : 

https://github.com/eslint/eslintrc/blob/bdce01aad747393d13cd1ae17d8280e54c9c5191/lib/config-array/config-array.js#L135-L156

**Example**
It makes linting fail when using `@babel/eslint-parser` as parser with babelOptions containing exclude as Regex:

```js
import { ESLint } from "eslint";

const cwd = 'somewhere'
const files = 'somefiles';

const eslintConfig = {
  parser: require.resolve("@babel/eslint-parser"),
  extends: ["eslint:recommended", "plugin:prettier/recommended"],
  plugins: ["eslint-plugin-prettier"],
  rules: {
    "prettier/prettier": "error",
  },
  parserOptions: {
    ecmaVersion: 2022,
    sourceType: "module",
    requireConfigFile: false,
    babelOptions: {
      exclude: /node_modules\/(core-js|@babel\/runtime)/,
      presets: [
        [
          require.resolve("@babel/preset-env"),
          {
            targets: [`defaults and supports es6-module`],
            useBuiltIns: "usage",
            corejs: { version: "3.21", proposals: true },
          },
        ],
      ],
      plugins: [
        [
          require.resolve("@babel/plugin-transform-runtime"),
          { useESModules: true },
        ],
      ],
    },
  },
};

const eslint = new ESLint({
  cwd,
  baseConfig: eslintConfig,
  resolvePluginsRelativeTo: __dirname,
});
const lintResults = await eslint.lintFiles(files);
```

Would trigger `0:0  error  Parsing error: .exclude must be a string/Function/RegExp, or an array of those` because the options are transformed to:

```js
babelOptions: {
    exclude: {}, // <= instead of keeping the regex
    presets: [ [Array] ],
    plugins: [ [Array] ]
  },
```

**Proposed change**

To solve this issue, mergeWithoutOverwrite need to check is the source[key] is a regex on top of checking for an object:

```diff
@@ -146,8 +146,12 @@ function mergeWithoutOverwrite(target, source) {
             mergeWithoutOverwrite(target[key], source[key]);
         } else if (target[key] === void 0) {
             if (isNonNullObject(source[key])) {
+              if (source[key] instanceof RegExp) {
+                target[key] = source[key];
+              } else {
                 target[key] = Array.isArray(source[key]) ? [] : {};
                 mergeWithoutOverwrite(target[key], source[key]);
+              }
             } else if (source[key] !== void 0) {
                 target[key] = source[key];
             }
```

**Comment by nzakas** [comment]
eslintrc config files intentionally don’t support regexes because they are meant to be serializable. Given that we are close to replacing the entire config system with a new one, I’m not sure that we should be making such changes at this point. I’d be curious what other team members think.

**Comment by mdjermanovic** [comment]
There are other ESLint features that expect eslintrc configs to be serializable, for example [caching](https://github.com/eslint/eslint/blob/18f5e05bce10503186989d81ca484abb185a2c9d/lib/cli-engine/lint-result-cache.js#L50), so adding support for non-serializable config entries looks like a relatively big change. Given that eslintrc functionalities are frozen because we're working on the new config system, I agree with @nzakas, we shouldn't be making such changes in eslintrc at this point.

Another question is whether the new flat config system should support regexes.

**Comment by nzakas** [comment]
There are a number of plugins that allow regexes to be passed in to their rules via JS config files right now, so I think we will end up needing to support it. The only serialization done with flat config is for caching, and it’s easy enough to convert a regex to a string for that purpose.

**Comment by nzakas** [comment]
Current config system is frozen, so we won’t be moving forward with such a change.
