### ISSUE TITLE
Problems with loading .eslintrc

### ISSUE THREAD

**Issue by theteladras** [eslint/eslintrc#83]
There seems to be an issue with loading the .eslintrc file:

```
Cannot read config file: /Users/sh/projects/tests/delete_me/.eslintrc.js Error: require() of ES Module
/Users/sh/projects/tests/delete_me/.eslintrc.js from
/Users/sh/projects/tests/delete_me/node_modules/@eslint/eslintrc/dist/eslintrc.cjs not supported. Instead change the
require of .eslintrc.js in /Users/sh/projects/tests/delete_me/node_modules/@eslint/eslintrc/dist/eslintrc.cjs to a dynamic
import() which is available in all CommonJS modules.
```
ESlint related dependency versions:
![image](https://user-images.githubusercontent.com/31168388/176233360-e7973566-f057-4cc1-9329-922c73c9e492.png)

In order to reproduce this issue, you can just initialise a Svelte project with having the eslint / prettier enabled, by running this:
`npm init svelte@next`.

PS project type set to module.

cc @[mdjermanovic](https://github.com/mdjermanovic)

**Comment by mdjermanovic** [comment]
ESLint does not yet support ESM config files.

This is a problem in [create-svelte](https://www.npmjs.com/package/create-svelte). I can confirm that `npm init svelte@next` currently creates an ESM eslint config file, but that has already been reverted in https://github.com/sveltejs/kit/pull/5293 (though, it seems that the update isn't published yet).

In the meantime, you can manually convert the config file to CJS and rename it to `.eslintrc.cjs`.

We expect that the new flat config system we're working on (https://github.com/eslint/eslint/issues/13481) will support ESM config files.

**Comment by nzakas** [comment]
Closing, as there is no task to do here.
